[package]
name = "pcap_replayer"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = "1.1.0"
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.32", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
etherparse = "0.13"
